# Generated by Django 5.2.2 on 2025-06-06 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='edited_on',
            field=models.DateField(auto_now=True, verbose_name='Edited on'),
        ),
    ]
